# Define constants to be used across the project
DEFAULT_NUM_ROUNDS = 200
DEFAULT_FRACTION_FIT = 0.1
DEFAULT_FRACTION_EVALUATE = 0.1
DEFAULT_LOCAL_EPOCHS = 4
NUM_CLIENTS = 100
BATCH_SIZE = 32
NUM_SHARDS_PER_PARTITION = 2
